/Loki/twist_mux:
  ros__parameters:
    locks:
      joy_priority:
        topic: teleop_joy/joy_priority
        timeout: 0.0
        priority: 100
      lock_all:
        topic: lock_all
        timeout: 0.0
        priority: 255

/Odin/twist_mux:
  ros__parameters:
    locks:
      joy_priority:
        topic: teleop_joy/joy_priority
        timeout: 0.0
        priority: 100
      lock_all:
        topic: lock_all
        timeout: 0.0
        priority: 255