base_driver:
  ros__parameters:
    motor_drives:
      drive0:
        node: 1
        x: -0.8910
        y: -0.7500
        type: 0
        leg_mesh: 0
        r_wheel: 0.2
        w_wheel: 0.16
        prp_gr_rt: 42
        prp_enc_ppr: 1024
        prp_max_rpm: 3000
        prp_sim_a: 1.5
        str_gr_rt: 42.8571429
        str_enc_ppr: 1024
        str_lim: 3.078027759
        str_sim_v: 4
      
      drive1:
        node: 2
        x: 0.8910
        y: -0.7500
        type: 0
        leg_mesh: 1
        r_wheel: 0.2
        w_wheel: 0.16
        prp_gr_rt: 42
        prp_enc_ppr: 1024
        prp_max_rpm: 3000
        prp_sim_a: 1.5
        str_gr_rt: 42.8571429
        str_enc_ppr: 1024
        str_lim: 3.078027759
        str_sim_v: 4
      
      drive2:
        node: 3
        x: 0.8910
        y: 0.7500
        type: 0
        leg_mesh: 2
        r_wheel: 0.2
        w_wheel: 0.16
        prp_gr_rt: 42
        prp_enc_ppr: 1024
        prp_max_rpm: 3000
        prp_sim_a: 1.5
        str_gr_rt: 42.8571429
        str_enc_ppr: 1024
        str_lim: 3.078027759
        str_sim_v: 4

      drive3:
        node: 4
        x: -0.8910
        y: 0.7500
        type: 0
        leg_mesh: 3
        r_wheel: 0.2
        w_wheel: 0.16
        prp_gr_rt: 42
        prp_enc_ppr: 1024
        prp_max_rpm: 3000
        prp_sim_a: 1.5
        str_gr_rt: 42.8571429
        str_enc_ppr: 1024
        str_lim: 3.078027759
        str_sim_v: 4

    batteries:
      bat0:
        id: 0.0
        type: 1.0
        x: 0.0
        y: 0.7500
        yaw: 0.0
        z: 0.75721
        bat_mesh: 0.0
      
      bat1:
        id: 20.0
        type: 0.0
        x: 0.0
        y: -0.7500
        yaw: 0.0
        z: 0.75721
        bat_mesh: 1.0

    io:
      io0:
        id: 20
        type: 0
        rl0_init_state: 0
        rl1_init_state: 0

      io1:
        id: 21
        type: 1
        rl0_init_state: 0
        rl1_init_state: 0

    pipes:
      pipes0:
        x1: -0.425
        y1: -0.7500
        x2:  0.425
        y2: -0.7500
        height: 0.68221
        space: 0.15

      pipesa1:
        x1:  0.425
        y1:  0.7500
        x2: -0.425
        y2:  0.7500
        height: 0.68221
        space: 0.15
    
    corners:
      corners0:
        type: 0
        corner_mesh: 1
        x: -0.425
        y: -0.7500
        z: 0.68221
        space: 0.15
        susp_ang: 0.25

      corner1:
        type: 1
        corner_mesh: 1 
        x:  0.425 
        y: -0.7500 
        z: 0.68221
        space: 0.15
        susp_ang: 0.25

      corner2:
        type: 2 
        corner_mesh: 1
        x:  0.425
        y:  0.7500
        z: 0.68221
        space: 0.15
        susp_ang: 0.25

      corner3:
        type: 3
        corner_mesh: 1
        x: -0.425
        y:  0.7500
        z: 0.68221
        space: 0.15
        susp_ang: 0.25


        
py_to_cpp:
  ros__parameters:

    can_interface_type: 0 #socket can enum is 0
    can_interface_name: can0
    
    motor_drives:
      drive0:
        node: 1
        x: -0.8910
        y: -0.7500
        type: 0
        leg_mesh: 0
        r_wheel: 0.2
        w_wheel: 0.16
        prp_gr_rt: 42
        prp_enc_ppr: 1024
        prp_max_rpm: 3000
        prp_sim_a: 1.5
        str_gr_rt: 42.8571429
        str_enc_ppr: 1024
        str_lim: 3.078027759
        str_sim_v: 4
      
      drive1:
        node: 2
        x: 0.8910
        y: -0.7500
        type: 0
        leg_mesh: 1
        r_wheel: 0.2
        w_wheel: 0.16
        prp_gr_rt: 42
        prp_enc_ppr: 1024
        prp_max_rpm: 3000
        prp_sim_a: 1.5
        str_gr_rt: 42.8571429
        str_enc_ppr: 1024
        str_lim: 3.078027759
        str_sim_v: 4
      
      drive2:
        node: 3
        x: 0.8910
        y: 0.7500
        type: 0
        leg_mesh: 2
        r_wheel: 0.2
        w_wheel: 0.16
        prp_gr_rt: 42
        prp_enc_ppr: 1024
        prp_max_rpm: 3000
        prp_sim_a: 1.5
        str_gr_rt: 42.8571429
        str_enc_ppr: 1024
        str_lim: 3.078027759
        str_sim_v: 4

      drive3:
        node: 4
        x: -0.8910
        y: 0.7500
        type: 0
        leg_mesh: 3
        r_wheel: 0.2
        w_wheel: 0.16
        prp_gr_rt: 42
        prp_enc_ppr: 1024
        prp_max_rpm: 3000
        prp_sim_a: 1.5
        str_gr_rt: 42.8571429
        str_enc_ppr: 1024
        str_lim: 3.078027759
        str_sim_v: 4


    batteries:
      bat0:
        id: 0.0
        type: 1.0
        x: 0.0
        y: 0.7500
        yaw: 0.0
        z: 0.75721
        bat_mesh: 0.0
      
      bat1:
        id: 20.0
        type: 0.0
        x: 0.0
        y: -0.7500
        yaw: 0.0
        z: 0.75721
        bat_mesh: 1.0

    io:
      io0:
        id: 20
        type: 0
        rl0_init_state: 0
        rl1_init_state: 0

      io1:
        id: 21
        type: 1
        rl0_init_state: 0
        rl1_init_state: 0

    pipes:
      pipes0:
        x1: -0.425
        y1: -0.7500
        x2:  0.425
        y2: -0.7500
        height: 0.68221
        space: 0.15

      pipesa1:
        x1:  0.425
        y1:  0.7500
        x2: -0.425
        y2:  0.7500
        height: 0.68221
        space: 0.15
    
    corners:
      corners0:
        type: 0
        corner_mesh: 1
        x: -0.425
        y: -0.7500
        z: 0.68221
        space: 0.15
        susp_ang: 0.25

      corner1:
        type: 1
        corner_mesh: 1 
        x:  0.425 
        y: -0.7500 
        z: 0.68221
        space: 0.15
        susp_ang: 0.25

      corner2:
        type: 2 
        corner_mesh: 1
        x:  0.425
        y:  0.7500
        z: 0.68221
        space: 0.15
        susp_ang: 0.25

      corner3:
        type: 3
        corner_mesh: 1
        x: -0.425
        y:  0.7500
        z: 0.68221
        space: 0.15
        susp_ang: 0.25


        
        